### ISSUE TITLE
Doesn't Seem to Work on CM4 Board

### ISSUE THREAD

**Issue by keenanjohnson** [RequestForCoffee/rpi-i2c-timings#1] opened 2021-11-11 19:05 UTC
Hello! I'm attempting to use this with a Raspberry Pi CM4 Board, which I thought should be processor identical to the Raspberry Pi 4, however, this utility doesn't seem to work for me.

When I inspect the /dev/ entry for the i2c interface on my board I see the following: bcm2835 (i2c@7e804000)

The registers match the comments in the source file here https://github.com/RequestForCoffee/rpi-i2c-timings/blob/master/rpi_i2c.c#L20

but when I run the utility to read the values, I get the following:

```
root@5582468:/usr/src# ./rpi-i2c 
Raspberry Pi I2C timing utility

To read current timing values, run the program without arguments.
To set new timing values: ./rpi-i2c <div.cdiv> <clkt.tout>

ARM peripheral address base: 0xfe000000
Could not open VPU core clock DebugFS path: No such file or directory
```

Any idea what could be wrong or how to troubleshoot it?

**Comment by RequestForCoffee** [comment] 2021-11-21 17:59
Your system appears to have trouble accessing the [VPU clock within DebugFS](https://github.com/RequestForCoffee/rpi-i2c-timings/blob/master/rpi_i2c.c#L33). I'm not familiar with the differences between the two boards, but a quick glance at their datasheets ([Pi 4B](https://datasheets.raspberrypi.com/rpi4/raspberry-pi-4-datasheet.pdf), [CM4](https://datasheets.raspberrypi.com/cm4/cm4-datasheet.pdf)) suggests the VideoCore may not be present/enabled on the CM4 (it's listed in the "hardware" section of the datasheet, 4B only).

Technically, this VPU core clock check is for informational purposes and may not be critical for the I2C clock changes. However, I do not have access to a CM4 board to test this out.

Would you mind trying the tool out with said core clock reading [block](https://github.com/RequestForCoffee/rpi-i2c-timings/blob/master/rpi_i2c.c#L79-L95) removed?

**Comment by keenanjohnson** [comment] 2021-11-22 17:32
Interesting and thanks for the response @RequestForCoffee! I'll will try removing that section and report back here!

**Comment by keenanjohnson** [comment] 2021-11-24 18:30
Just to update this, as you suggested, removing the VPU clock section did allow me to run this utility on my CM4.

```
root@8af8382:/usr/src# ./rpi-i2c 
Raspberry Pi I2C timing utility

To read current timing values, run the program without arguments.
To set new timing values: ./rpi-i2c <div.cdiv> <clkt.tout>

ARM peripheral address base: 0xfe000000
I2C1 controller address base: 0xfe804000
DIV.CDIV: 1500
CLKT.TOUT: 64
```

**Comment by RequestForCoffee** [comment] 2021-11-24 20:00
I'm glad to hear that. Now for the important bit - are you able to adjust the clock and verify its behavior, e.g. using a logic analyzer, or prolonged testing with a sensor that's sensitive to the clock speed?

**Comment by keenanjohnson** [comment] 2021-11-24 20:37
It seems that way! Unfortunately, I don't have a logic analyzer handy right now to 100% verify but I have some sensitive ish sensors that seemed to confirm changes.

For example:

```
root@8af8382:/usr/src# ./rpi-i2c 5000 20000
Raspberry Pi I2C timing utility

To read current timing values, run the program without arguments.
To set new timing values: ./rpi-i2c <div.cdiv> <clkt.tout>

ARM peripheral address base: 0xfe000000
I2C1 controller address base: 0xfe804000
DIV.CDIV: 1500
CLKT.TOUT: 64
Updating delay values to: FEDL=312, REDL=1250.
Timing values updated: CDIV=5000, CLKT=20000.
root@8af8382:/usr/src# ./rpi-i2c 
Raspberry Pi I2C timing utility

To read current timing values, run the program without arguments.
To set new timing values: ./rpi-i2c <div.cdiv> <clkt.tout>

ARM peripheral address base: 0xfe000000
I2C1 controller address base: 0xfe804000
DIV.CDIV: 5000
CLKT.TOUT: 20000
```

I'm not sure if there is an easy way to detect if this program is running on a Raspberry Pi 4 vs a CM4, so perhaps I can just add a note in the readme that describes removing the VPU section as you suggested for others that might want to use this utility?

Thanks again for your help!

**Comment by RequestForCoffee** [comment] 2021-11-24 21:13
I would suggest running such sensors for a longer period of time. At some point, when experimenting with the SCD30 I found it sometimes started misbehaving only after several days of non-stop operation.

I don't have my dev setup handy right now, but I quickly cobbled together a change to make the VPU clock printing optional/non-fatal. Would you mind giving it a shot from the `cm4` branch to verify it compiles and still works as intended?

**Comment by keenanjohnson** [comment] 2021-11-24 21:32
Wow small world. The SCD30 is exactly the sensor that led me down this rabbit hole of I2C debugging. We've determined for us that the long term stability problems are related to the Raspberry Pi Hardware I2C incorrectly handling clock-stretching, which the SCD30 requires. [We resolved the issue here by switching to the i2c-gpio](https://github.com/Ribbit-Network/ribbit-network-frog-sensor/issues/61) (software i2c) implementation at a lower clock rate (10kHz) which handles clock stretching correctly and appears to have resolved our issue. Hope that's helpful!

I can verify that branch now.

**Comment by keenanjohnson** [comment] 2021-11-24 21:37
Yeah that branch works great on a CM4. Thanks for the help!

```
root@8af8382:/usr/src# ./rpi-i2c 
Raspberry Pi I2C timing utility

To read current timing values, run the program without arguments.
To set new timing values: ./rpi-i2c <div.cdiv> <clkt.tout>

ARM peripheral address base: 0xfe000000
Could not open VPU core clock DebugFS path
I2C1 controller address base: 0xfe804000
DIV.CDIV: 1500
CLKT.TOUT: 64
```

**Comment by RequestForCoffee** [comment] 2021-11-24 21:49
Interestingly enough, while this helped reduce their frequency significanty, I would still get some very intermittent stability issues. Sometimes being spaced days or weeks apart, running a logic analyzer recording at 10-100KHz for days on end wasn't very feasible either. Then again, it could have been due to interplay with other air quality sensors on the same circuit, or just buggy code on my end.

Regardless, happy to hear the `cm4` branch works - thanks for giving it a try. I'll go ahead and merge it, closing the issue. Please feel free to open a new one if you need any other help.

**Closed as completed** 2021-11-24 21:50 UTC

**Comment by keenanjohnson** [comment] 2021-11-24 22:07
Thanks! Yeah as I mentioned, just lowering the clock frequency isn't enough as the raspberry pi i2c hardware doesn't properly handle an extension to the i2c protocol called clock stretching. You can switch to a bit banging implementation fairly easily which handles the clock stretching correctly which should clear up your issues if you ever pick up your project! Let me know if you do and if you need any assistance on that :)
